// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradesparqDBContext;

#nullable disable

namespace Tradesparq.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tradesparq.Model.Company.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .HasColumnType("longtext");

                    b.Property<string>("Uname")
                        .HasColumnType("longtext");

                    b.Property<string>("Uuid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Var")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Uuid" }, "IX_companies_UUID")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Company.Shipments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("BatchId")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Buyer")
                        .HasColumnType("longtext");

                    b.Property<string>("BuyerAddr")
                        .HasColumnType("longtext");

                    b.Property<string>("BuyerId")
                        .HasColumnType("longtext");

                    b.Property<string>("CarrierName")
                        .HasColumnType("longtext");

                    b.Property<string>("ContainerNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Customs")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSource")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("DestCountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("DestPort")
                        .HasColumnType("longtext");

                    b.Property<string>("ExporterId")
                        .HasColumnType("longtext");

                    b.Property<string>("HsCode")
                        .HasColumnType("longtext");

                    b.Property<string>("IdShipments")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImporterId")
                        .HasColumnType("longtext");

                    b.Property<string>("MasterBillNo")
                        .HasColumnType("longtext");

                    b.Property<string>("OrigCountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("OrigPort")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("ProdDesc")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("QuantityUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierAddr")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierId")
                        .HasColumnType("longtext");

                    b.Property<int?>("Teu")
                        .HasColumnType("int");

                    b.Property<string>("Tncoterms")
                        .HasColumnType("longtext");

                    b.Property<string>("TransType")
                        .HasColumnType("longtext");

                    b.Property<string>("VesselName")
                        .HasColumnType("longtext");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdShipments")
                        .IsUnique();

                    b.HasIndex(new[] { "IdShipments" }, "IX_companies_Id_shippment")
                        .IsUnique();

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Emails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Faxs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.ToTable("Faxs", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.PhoneNumbers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.ToTable("PhoneNumbers", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.PostalCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.ToTable("PostalCodes", (string)null);
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Cities", b =>
                {
                    b.HasOne("Tradesparq.Model.Company.Companies", null)
                        .WithMany("City")
                        .HasForeignKey("CompaniesId");
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Emails", b =>
                {
                    b.HasOne("Tradesparq.Model.Company.Companies", null)
                        .WithMany("Email")
                        .HasForeignKey("CompaniesId");
                });

            modelBuilder.Entity("Tradesparq.Model.Info.Faxs", b =>
                {
                    b.HasOne("Tradesparq.Model.Company.Companies", null)
                        .WithMany("Fax")
                        .HasForeignKey("CompaniesId");
                });

            modelBuilder.Entity("Tradesparq.Model.Info.PhoneNumbers", b =>
                {
                    b.HasOne("Tradesparq.Model.Company.Companies", null)
                        .WithMany("PhoneNumber")
                        .HasForeignKey("CompaniesId");
                });

            modelBuilder.Entity("Tradesparq.Model.Info.PostalCodes", b =>
                {
                    b.HasOne("Tradesparq.Model.Company.Companies", null)
                        .WithMany("PostalCode")
                        .HasForeignKey("CompaniesId");
                });

            modelBuilder.Entity("Tradesparq.Model.Company.Companies", b =>
                {
                    b.Navigation("City");

                    b.Navigation("Email");

                    b.Navigation("Fax");

                    b.Navigation("PhoneNumber");

                    b.Navigation("PostalCode");
                });
#pragma warning restore 612, 618
        }
    }
}
